#env:
  #TERM: alacritty
#window:
  #dimensions:
  #  columns: 0
  #  lines: 0
  #position:
  #  x: 0
  #  y: 0
  #padding:
  #  x: 0
  #  y: 0
  #dynamic_padding: false
  #decorations: full
  #startup_mode: Windowed
  #title: Alacritty
  #class:
    #instance: Alacritty
    #general: Alacritty
  #gtk_theme_variant: None
#scrolling:
  #history: 10000
  #multiplier: 3
font:
  normal:
    family: Inconsolata
  size: 12.0
  #offset:
  #  x: 0
  #  y: 0
  #glyph_offset:
  #  x: 0
  #  y: 0
#draw_bold_text_with_bright_colors: false
#colors:
  #primary:
  #  background: '#000000'
  #  foreground: '#eaeaea'
    #dim_foreground: '#9a9a9a'
    #bright_foreground: '#ffffff'
  #cursor:
  #  text: '#000000'
  #  cursor: '#ffffff'
  #selection:
  #  text: '#eaeaea'
  #  background: '#404040'
  #normal:
  #  black:   '#000000'
  #  red:     '#d54e53'
  #  green:   '#b9ca4a'
  #  yellow:  '#e6c547'
  #  blue:    '#7aa6da'
  #  magenta: '#c397d8'
  #  cyan:    '#70c0ba'
  #  white:   '#eaeaea'
  #bright:
  #  black:   '#666666'
  #  red:     '#ff3334'
  #  green:   '#9ec400'
  #  yellow:  '#e7c547'
  #  blue:    '#7aa6da'
  #  magenta: '#b77ee0'
  #  cyan:    '#54ced6'
  #  white:   '#ffffff'
  #dim:
  #  black:   '#000000'
  #  red:     '#8c3336'
  #  green:   '#7a8530'
  #  yellow:  '#97822e'
  #  blue:    '#506d8f'
  #  magenta: '#80638e'
  #  cyan:    '#497e7a'
  #  white:   '#9a9a9a'
  #indexed_colors: []

# Visual Bell
#visual_bell:
#  animation: EaseOutExpo
#  duration: 0
#  color: '#ffffff'
#background_opacity: 1.0
#selection:
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
dynamic_title: true
cursor:
  style: Block
  #unfocused_hollow: true
live_config_reload: true
#shell:
#  program: /bin/bash
#  args:
#    - --login
#mouse:
  #double_click: { threshold: 300 }
  #triple_click: { threshold: 300 }
  #hide_when_typing: false
  #url:
    #launcher:
    #  program: xdg-open
    #  args: []
    #modifiers: None
#mouse_bindings:
#  - { mouse: Middle, action: PasteSelection }
#key_bindings:
  # (Windows, Linux, and BSD only)
  #- { key: V,        mods: Control|Shift, action: Paste            }
  #- { key: C,        mods: Control|Shift, action: Copy             }
  #- { key: Insert,   mods: Shift,         action: PasteSelection   }
  #- { key: Key0,     mods: Control,       action: ResetFontSize    }
  #- { key: Equals,   mods: Control,       action: IncreaseFontSize }
  #- { key: Add,      mods: Control,       action: IncreaseFontSize }
  #- { key: Subtract, mods: Control,       action: DecreaseFontSize }
  #- { key: Minus,    mods: Control,       action: DecreaseFontSize }

  # (Windows only)
  #- { key: Return,   mods: Alt,           action: ToggleFullscreen }

  # (macOS only)
  #- { key: Key0,   mods: Command,         action: ResetFontSize    }
  #- { key: Equals, mods: Command,         action: IncreaseFontSize }
  #- { key: Add,    mods: Command,         action: IncreaseFontSize }
  #- { key: Minus,  mods: Command,         action: DecreaseFontSize }
  #- { key: K,      mods: Command,         action: ClearHistory     }
  #- { key: K,      mods: Command,         chars: "\x0c"            }
  #- { key: V,      mods: Command,         action: Paste            }
  #- { key: C,      mods: Command,         action: Copy             }
  #- { key: H,      mods: Command,         action: Hide             }
  #- { key: M,      mods: Command,         action: Minimize         }
  #- { key: Q,      mods: Command,         action: Quit             }
  #- { key: W,      mods: Command,         action: Quit             }
  #- { key: F,      mods: Command|Control, action: ToggleFullscreen }

  #- { key: Paste,                    action: Paste                            }
  #- { key: Copy,                     action: Copy                             }
  #- { key: L,         mods: Control, action: ClearLogNotice                   }
  #- { key: L,         mods: Control, chars: "\x0c"                            }
  #- { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  #- { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  #- { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  #- { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
#debug:
  #render_timer: false
  #persistent_logging: false
  #log_level: Warn
  #print_events: false
